name: Run function tests and install sample data

on:
    push:
        branches:
            - liutaodemo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout function test repo
        uses: actions/checkout@v3
        with:
          repository: opensearch-project/opensearch-dashboards-functional-test
          path: functionaltest

      - name: Install dependencies for function test
        run: |
          cd functiontest
          npm install

