name: Run function tests and install sample data

on:
    push:
        branches:
            - liutaodemo

jobs:
  # The first job in this workflow, it is praparing the ubuntu
  prepare-ubuntu:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: prepare-ubuntu -> Step1
          run: echo "hello"
  # This second job in this workflow, it is configuring the function test
  config-test:
      needs: prepare-ubuntu
      runs-on: ubuntu-latest
      steps:
        - name: Checkout function test repo
          uses: actions/checkout@v3
          with:
            repository: opensearch-project/opensearch-dashboards-functional-test

        - name: Install dependencies for function test
          run: |
            npm install
            npm install -g yarn
            yarn cypress run --spec "cypress/integration/core-opensearch-dashboards/opensearch-dashboards/*.js" --config "baseUrl=https://publicdemo-1997563990.us-west-2.elb.amazonaws.com/" --env "openSearchUrl=https://publicdemo-1997563990.us-west-2.elb.amazonaws.com,SECURITY_ENABLED=true,username=${{ secrets.OSD_USER }},password=${{ secrets.OSD_PASSWORD }}"

